// Code generated by goyacc -o y.go -p yy classad.y. DO NOT EDIT.

//line classad.y:2
package parser

import (
	__yyfmt__ "fmt"

	"github.com/PelicanPlatform/classad/ast"
) //line classad.y:2

//line classad.y:10
type yySymType struct {
	yys      int
	node     ast.Node
	expr     ast.Expr
	classad  *ast.ClassAd
	attr     *ast.AttributeAssignment
	attrs    []*ast.AttributeAssignment
	exprlist []ast.Expr
	str      string
	integer  int64
	real     float64
	boolean  bool
}

const IDENTIFIER = 57346
const STRING_LITERAL = 57347
const INTEGER_LITERAL = 57348
const REAL_LITERAL = 57349
const BOOLEAN_LITERAL = 57350
const UNDEFINED = 57351
const ERROR = 57352
const INT64_MIN_MAGNITUDE = 57353
const ELVIS = 57354
const OR = 57355
const AND = 57356
const EQ = 57357
const NE = 57358
const IS = 57359
const ISNT = 57360
const LE = 57361
const GE = 57362
const LSHIFT = 57363
const RSHIFT = 57364
const URSHIFT = 57365
const UNARY = 57366

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING_LITERAL",
	"INTEGER_LITERAL",
	"REAL_LITERAL",
	"BOOLEAN_LITERAL",
	"UNDEFINED",
	"ERROR",
	"INT64_MIN_MAGNITUDE",
	"ELVIS",
	"'?'",
	"':'",
	"OR",
	"AND",
	"'|'",
	"'^'",
	"'&'",
	"EQ",
	"NE",
	"IS",
	"ISNT",
	"'<'",
	"'>'",
	"LE",
	"GE",
	"LSHIFT",
	"RSHIFT",
	"URSHIFT",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UNARY",
	"'!'",
	"'~'",
	"'.'",
	"'['",
	"'('",
	"']'",
	"';'",
	"'='",
	"')'",
	"'{'",
	"'}'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line classad.y:327

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 189

var yyAct = [...]int8{
	12, 13, 25, 23, 21, 19, 121, 18, 114, 113,
	17, 120, 24, 22, 119, 112, 31, 44, 37, 38,
	40, 41, 42, 16, 115, 9, 84, 10, 20, 8,
	9, 118, 67, 68, 3, 77, 80, 15, 75, 70,
	72, 73, 74, 27, 26, 4, 83, 62, 63, 28,
	29, 33, 43, 34, 50, 49, 89, 88, 35, 87,
	94, 95, 96, 97, 48, 47, 101, 102, 45, 107,
	46, 86, 108, 98, 99, 100, 111, 103, 104, 105,
	90, 91, 92, 93, 85, 69, 117, 81, 116, 82,
	106, 7, 31, 44, 37, 38, 40, 41, 42, 71,
	64, 65, 66, 31, 44, 37, 38, 40, 41, 42,
	76, 1, 67, 68, 5, 122, 109, 110, 123, 27,
	26, 124, 125, 78, 11, 28, 29, 33, 43, 34,
	27, 26, 79, 14, 35, 30, 28, 29, 33, 43,
	34, 59, 60, 61, 32, 35, 31, 44, 37, 38,
	40, 41, 42, 55, 56, 57, 58, 51, 52, 53,
	54, 39, 6, 36, 2, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 33, 43, 34, 0, 0, 0, 0, 35,
}

var yyPact = [...]int16{
	-6, -32768, -32768, 87, -13, -32768, -32768, -17, -32768, 87,
	99, -32768, -32768, -32768, 55, 49, 47, 37, 35, 137,
	129, 113, 16, 67, -32768, 73, 88, 99, 99, 99,
	-32768, -3, -32768, 106, 99, 99, -32768, -32768, -32768, 82,
	-32768, -32768, -32768, 87, -32768, 12, 99, 99, 99, 99,
	99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
	99, 99, 99, 99, 99, 99, 99, 86, 99, 142,
	-32768, -32768, -32768, -32768, -32768, 99, -32768, -30, -38, -40,
	-32768, -32768, -18, 74, 99, 49, 47, 37, 35, 137,
	129, 129, 129, 129, 113, 113, 113, 113, 16, 16,
	16, 67, 67, -32768, -32768, -32768, -32768, -11, -7, -31,
	-37, -32768, -32768, -32768, 99, -32768, 99, -32768, -32768, -32768,
	99, 99, -32768, -32768, -32768, -32768,
}

var yyPgo = [...]uint8{
	0, 164, 163, 45, 162, 114, 161, 0, 144, 135,
	2, 12, 3, 13, 4, 28, 5, 7, 10, 23,
	37, 133, 1, 132, 123, 117, 116, 111,
}

var yyR1 = [...]int8{
	0, 27, 1, 2, 3, 3, 5, 5, 4, 7,
	22, 22, 22, 21, 21, 20, 20, 19, 19, 18,
	18, 17, 17, 16, 16, 16, 16, 16, 15, 15,
	15, 15, 15, 14, 14, 14, 14, 13, 13, 13,
	12, 12, 12, 12, 11, 11, 11, 11, 11, 11,
	10, 10, 10, 10, 10, 9, 9, 9, 9, 9,
	9, 8, 8, 8, 8, 8, 8, 6, 6, 24,
	24, 23, 23, 26, 26, 25, 25, 25,
}

var yyR2 = [...]int8{
	0, 1, 3, 3, 1, 3, 0, 1, 3, 1,
	1, 5, 4, 1, 3, 1, 3, 1, 3, 1,
	3, 1, 3, 1, 3, 3, 3, 3, 1, 3,
	3, 3, 3, 1, 3, 3, 3, 1, 3, 3,
	1, 3, 3, 3, 1, 2, 2, 2, 2, 2,
	1, 3, 4, 3, 4, 1, 1, 2, 3, 3,
	1, 1, 1, 1, 1, 1, 1, 1, 2, 0,
	1, 1, 3, 0, 1, 1, 3, 3,
}

var yyChk = [...]int16{
	-32768, -27, -1, 40, -3, -5, -4, 4, 42, 43,
	44, -5, -7, -22, -21, -20, -19, -18, -17, -16,
	-15, -14, -13, -12, -11, -10, 32, 31, 37, 38,
	-9, 4, -8, 39, 41, 46, -2, 6, 7, -6,
	8, 9, 10, 40, 5, 13, 15, 16, 17, 18,
	19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
	29, 30, 31, 32, 33, 34, 35, 39, 40, 12,
	-11, 11, -11, -11, -11, 41, 4, -7, -24, -23,
	-7, 5, -3, -7, 14, -20, -19, -18, -17, -16,
	-15, -15, -15, -15, -14, -14, -14, -14, -13, -13,
	-13, -12, -12, -11, -11, -11, 4, -7, -10, -26,
	-25, -7, 45, 47, 48, 42, 14, -22, 42, 45,
	48, 43, -7, -22, -7, -7,
}

var yyDef = [...]int8{
	0, -2, 1, 6, 0, 4, 7, 0, 2, 6,
	0, 5, 8, 9, 10, 13, 15, 17, 19, 21,
	23, 28, 33, 37, 40, 44, 0, 0, 0, 0,
	50, 56, 55, 0, 0, 69, 60, 61, 62, 63,
	64, 65, 66, 6, 67, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	45, 46, 47, 48, 49, 73, 57, 0, 0, 70,
	71, 68, 0, 0, 0, 14, 16, 18, 20, 22,
	24, 25, 26, 27, 29, 30, 31, 32, 34, 35,
	36, 38, 39, 41, 42, 43, 51, 0, 53, 0,
	74, 75, 58, 59, 0, 3, 0, 12, 52, 54,
	0, 0, 72, 11, 76, 77,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 37, 3, 3, 3, 35, 19, 3,
	41, 45, 33, 31, 48, 32, 39, 34, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 14, 43,
	24, 44, 25, 13, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 40, 3, 42, 18, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 46, 17, 47, 38,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 15, 16, 20, 21, 22, 23, 26, 27, 28,
	29, 30, 36,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:73
		{
			if lex, ok := yylex.(interface{ SetResult(ast.Node) }); ok {
				lex.SetResult(yyDollar[1].classad)
			}
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:82
		{
			yyVAL.classad = &ast.ClassAd{Attributes: yyDollar[2].attrs}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:87
		{
			yyVAL.classad = &ast.ClassAd{Attributes: yyDollar[2].attrs}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:96
		{
			if yyDollar[1].attr != nil {
				yyVAL.attrs = []*ast.AttributeAssignment{yyDollar[1].attr}
			} else {
				yyVAL.attrs = []*ast.AttributeAssignment{}
			}
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:98
		{
			if yyDollar[3].attr != nil {
				yyVAL.attrs = append(yyDollar[1].attrs, yyDollar[3].attr)
			} else {
				yyVAL.attrs = yyDollar[1].attrs
			}
		}
	case 6:
		yyDollar = yyS[yypt-0 : yypt+1]
//line classad.y:103
		{
			yyVAL.attr = nil
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:105
		{
			yyVAL.attr = yyDollar[1].attr
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:110
		{
			yyVAL.attr = &ast.AttributeAssignment{Name: yyDollar[1].str, Value: yyDollar[3].expr}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:115
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:120
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 11:
		yyDollar = yyS[yypt-5 : yypt+1]
//line classad.y:122
		{
			yyVAL.expr = &ast.ConditionalExpr{Condition: yyDollar[1].expr, TrueExpr: yyDollar[3].expr, FalseExpr: yyDollar[5].expr}
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
//line classad.y:124
		{
			yyVAL.expr = &ast.ElvisExpr{Left: yyDollar[1].expr, Right: yyDollar[4].expr}
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:129
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:131
		{
			yyVAL.expr = &ast.BinaryOp{Op: "||", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:136
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:138
		{
			yyVAL.expr = &ast.BinaryOp{Op: "&&", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:143
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:145
		{
			yyVAL.expr = &ast.BinaryOp{Op: "|", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:150
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:152
		{
			yyVAL.expr = &ast.BinaryOp{Op: "^", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:157
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:159
		{
			yyVAL.expr = &ast.BinaryOp{Op: "&", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:164
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:166
		{
			yyVAL.expr = &ast.BinaryOp{Op: "==", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:168
		{
			yyVAL.expr = &ast.BinaryOp{Op: "!=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:170
		{
			yyVAL.expr = &ast.BinaryOp{Op: "is", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:172
		{
			yyVAL.expr = &ast.BinaryOp{Op: "isnt", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:177
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:179
		{
			yyVAL.expr = &ast.BinaryOp{Op: "<", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:181
		{
			yyVAL.expr = &ast.BinaryOp{Op: ">", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:183
		{
			yyVAL.expr = &ast.BinaryOp{Op: "<=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:185
		{
			yyVAL.expr = &ast.BinaryOp{Op: ">=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:190
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:192
		{
			yyVAL.expr = &ast.BinaryOp{Op: "<<", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:194
		{
			yyVAL.expr = &ast.BinaryOp{Op: ">>", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:196
		{
			yyVAL.expr = &ast.BinaryOp{Op: ">>>", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:201
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:203
		{
			yyVAL.expr = &ast.BinaryOp{Op: "+", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:205
		{
			yyVAL.expr = &ast.BinaryOp{Op: "-", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:210
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:212
		{
			yyVAL.expr = &ast.BinaryOp{Op: "*", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:214
		{
			yyVAL.expr = &ast.BinaryOp{Op: "/", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:216
		{
			yyVAL.expr = &ast.BinaryOp{Op: "%", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:221
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
//line classad.y:223
		{
			yyVAL.expr = &ast.UnaryOp{Op: "-", Expr: yyDollar[2].expr}
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
//line classad.y:225
		{
			yyVAL.expr = &ast.IntegerLiteral{Value: -9223372036854775808}
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line classad.y:227
		{
			yyVAL.expr = &ast.UnaryOp{Op: "+", Expr: yyDollar[2].expr}
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line classad.y:229
		{
			yyVAL.expr = &ast.UnaryOp{Op: "!", Expr: yyDollar[2].expr}
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line classad.y:231
		{
			yyVAL.expr = &ast.UnaryOp{Op: "~", Expr: yyDollar[2].expr}
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:236
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:238
		{
			yyVAL.expr = &ast.SelectExpr{Record: yyDollar[1].expr, Attr: yyDollar[3].str}
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
//line classad.y:240
		{
			yyVAL.expr = &ast.SubscriptExpr{Container: yyDollar[1].expr, Index: yyDollar[3].expr}
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:242
		{
			yyVAL.expr = &ast.ElvisExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
//line classad.y:244
		{
			yyVAL.expr = &ast.FunctionCall{Name: yyDollar[1].str, Args: yyDollar[3].exprlist}
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:249
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:251
		{
			name, scope := ParseScopedIdentifier(yyDollar[1].str)
			yyVAL.expr = ast.NewAttributeReference(name, scope)
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
//line classad.y:256
		{
			// A leading-dot reference (".A") is a plain reference in the
			// reference engine (".A" resolves identically to "A").
			name, scope := ParseScopedIdentifier(yyDollar[2].str)
			yyVAL.expr = ast.NewAttributeReference(name, scope)
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:263
		{
			yyVAL.expr = ast.Parenthesize(yyDollar[2].expr)
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:265
		{
			yyVAL.expr = &ast.ListLiteral{Elements: yyDollar[2].exprlist}
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:267
		{
			yyVAL.expr = &ast.RecordLiteral{ClassAd: yyDollar[1].classad}
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:272
		{
			yyVAL.expr = &ast.IntegerLiteral{Value: yyDollar[1].integer}
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:274
		{
			yyVAL.expr = &ast.RealLiteral{Value: yyDollar[1].real}
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:276
		{
			yyVAL.expr = &ast.StringLiteral{Value: yyDollar[1].str}
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:278
		{
			yyVAL.expr = &ast.BooleanLiteral{Value: yyDollar[1].boolean}
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:280
		{
			yyVAL.expr = &ast.UndefinedLiteral{}
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:282
		{
			yyVAL.expr = &ast.ErrorLiteral{}
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:288
		{
			yyVAL.str = yyDollar[1].str
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
//line classad.y:290
		{
			yyVAL.str = yyDollar[1].str + yyDollar[2].str
		}
	case 69:
		yyDollar = yyS[yypt-0 : yypt+1]
//line classad.y:295
		{
			yyVAL.exprlist = []ast.Expr{}
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:297
		{
			yyVAL.exprlist = yyDollar[1].exprlist
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:302
		{
			yyVAL.exprlist = []ast.Expr{yyDollar[1].expr}
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:304
		{
			yyVAL.exprlist = append(yyDollar[1].exprlist, yyDollar[3].expr)
		}
	case 73:
		yyDollar = yyS[yypt-0 : yypt+1]
//line classad.y:313
		{
			yyVAL.exprlist = []ast.Expr{}
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:315
		{
			yyVAL.exprlist = yyDollar[1].exprlist
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line classad.y:320
		{
			yyVAL.exprlist = []ast.Expr{yyDollar[1].expr}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:322
		{
			yyVAL.exprlist = append(yyDollar[1].exprlist, yyDollar[3].expr)
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line classad.y:324
		{
			yyVAL.exprlist = append(yyDollar[1].exprlist, yyDollar[3].expr)
		}
	}
	goto yystack /* stack new state and value */
}
