package vm

// parityCorpusExprs are expression edge cases lifted from the classad package's
// C++ differential-parity tests (classad/cpp_parity_test.go). They are seeded
// into the vm differential fuzz corpus and exercised by the differential test,
// so every AST evaluation edge case the reference engine was hardened against is
// also checked for vm/evaluator parity.
var parityCorpusExprs = []string{
	"1 / 2",
	"7 / 2",
	"-7 / 2",
	"6 / 3",
	"1.0 / 2.0",
	"7 % 3",
	"-7 % 3",
	"6 & 3",
	"6 | 1",
	"6 ^ 3",
	"1 << 4",
	"-8 >> 1",
	"-8 >>> 1",
	"~5",
	"1 << 64",
	"6 & 3.0",
	"6 & true",
	"6 & undefined",
	"~undefined",
	"-29 >>> 0",
	"5 >>> 0",
	"-1 >>> 0",
	"-8 >> 64",
	"-8 >> 2",
	"\"B\" < \"a\"",
	"\"a\" < \"B\"",
	"\"abc\" == \"ABC\"",
	"\"abc\" != \"ABC\"",
	"\"abc\" =?= \"ABC\"",
	"\"abc\" =!= \"ABC\"",
	"true < false",
	"true + 1",
	"true * 3",
	"true == 1",
	"2 == true",
	"true % 2",
	"-true",
	"false && error",
	"error && false",
	"true || undefined",
	"undefined && false",
	"undefined && true",
	"undefined || true",
	"!undefined",
	"!1",
	"!0",
	"1 && true",
	"0 && true",
	"{1, 2}[5]",
	"{1, 2}[-1]",
	"{}[0]",
	"{1, 2, 3}[0]",
	"-undefined",
	"+undefined",
	"1 ? \"a\" : \"b\"",
	"0 ? \"a\" : \"b\"",
	"undefined ? 1 : 2",
	"\"x\" ? 1 : 2",
	"floor(undefined)",
	"round(undefined)",
	"round(true)",
	"floor(true)",
	"ceiling(false)",
	"round(2.5)",
	"round(3.5)",
	"round(0.5)",
	"round(-2.5)",
	"round(2.6)",
	"round(188587117711686808)",
	"floor(9223372036854775807)",
	"pow(2, 3)",
	"pow(2, -1)",
	"pow(2, true)",
	"pow(true, true)",
	"floor(\"2.5\")",
	"round(\"3.5\")",
	"floor(\"abc\")",
	"pow(\"2\", \"3\")",
	"quantize(\"10\", \"3\")",
	"pow(undefined, 2)",
	"quantize(undefined, 4)",
	"split(undefined)",
	"string(undefined)",
	"bool(undefined)",
	"bool(\"TRUE\")",
	"bool(\"x\")",
	"\"Hello\" >= \"a\"",
	"\"Hello World\" >= \"a,b,c\"",
	"strcmp(undefined, \"a\")",
	"toUpper(5)",
	"toUpper(true)",
	"toLower(1.5)",
	"stricmp(true, \"x\")",
	"length(\"hello\")",
	"length({1, 2})",
	"suBstr(\"hello\", 0, 2)",
	"STRCAT(\"a\", \"b\")",
	"ToLower(\"ABC\")",
	"IfThenElse(true, 1, 2)",
	"string({})",
	"string({1, 2})",
	"string({\"a\", 1})",
	"string({true, undefined})",
	"string({{1}, 2})",
	"strcat({1, 2}, \"!\")",
	"string({1, 1+1})",
	"string({(a + 1)})",
	"string({(undefined ? error : false)})",
	"toUpper({a + 1})",
	"strcat({1, 2}, x0)",
	"toUpper({1})",
	"stricmp({}, 1)",
	"ifThenElse(1, 10, 20)",
	"ifThenElse(0, 10, 20)",
	"ifThenElse(1.5, 10, 20)",
	"ifThenElse(undefined, 1, 2)",
	"ifThenElse(\"x\", 1, 2)",
	"real(true)",
	"real(false)",
	"int(true)",
	"int(\"42\")",
	"int(\"1.9\")",
	"int(\"-3.7\")",
	"int(\" 5 \")",
	"int(\"1e-10\")",
	"int(\"abc\")",
	"int(\"\")",
	"real(\"3.14\")",
	"real(\"x\")",
	"quantize(true, false)",
	"quantize(7, 0)",
	"quantize(5, 3)",
	"quantize(8, 3)",
	"quantize(true, 2)",
	"quantize(5, true)",
	"quantize(12, {5, 10, 15, 20})",
	"quantize(25, {5, 10, 15, 20})",
	"substr(error, 1, 2)",
	"substr(error, undefined, 1)",
	"substr(error, error, undefined)",
	"substr(\"hello\", 1, -1)",
	"substr(\"hello\", -2)",
	"substr(\"hello\", -1, -1)",
	"substr(\"hello\", 0, -1)",
	"substr(\"hello\", 2, 100)",
	"substr(\"hello\", 10)",
	"strcmp(error, undefined)",
	"stricmp(undefined, error)",
	"member(error, undefined)",
	"member({}, {\"x y\"})",
	"member(1, {1.0})",
	"member(\"ABC\", {\"abc\"})",
	"member(1, {\"a\", 1})",
	"member(5, {\"a\"})",
	"1 / 0",
	"1 / 0.0",
	"1.0 / 0.0",
	"-1.0 / 0.0",
	"0.0 / 0.0",
	"5.0 / 2.0",
	"string(1.5)",
	"string(0.0)",
	"string(true)",
	"string(1)",
	"strcat(1, \"x\")",
	"strcat(true, \"x\")",
	"strcat(true, undefined)",
	"0.1 + 0.2 == 0.3",
	"1 == 1.0000000001",
	"1.0 == 1",
	"undefined == undefined",
	"\"a\" == 1",
	"{1} == 1",
	"{1, 2} == {1, 2}",
	"{1} =?= {1}",
	"{1} =!= {2}",
	"{1} =?= 1",
}
